env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent: off
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-console: off
  no-template-curly-in-string: error
  dot-notation: error
  no-useless-concat: error
  no-var: warn
  prefer-const: error
  prefer-arrow-callback: warn
  no-useless-constructor: error
  object-shorthand: warn
  spaced-comment: warn
  no-unsafe-negation: error
  no-eval: error
  no-implied-eval: error
  no-labels: error
  no-shadow: warn
  no-lone-blocks: warn
  no-new: error
  no-unused-expressions: error
  consistent-this:
      - error
      - self
  brace-style:
      - warn
      - allman
  eqeqeq:
      - error
      - smart
