env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent: off
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-console: off
  prefer-const: error
